### ISSUE TITLE
HAProxy HealthCheck Endpoint Note

### ISSUE THREAD

**Issue by robertoestivill** [vert-x3/vertx-openshift-cartridge#1]
I created an autoscaling Vertx app using this cartridge and was not able to hit my application from the internet. I was receiving a 503 and the haproxy page was not displaying any online instance although the push and deployment of the app was correct and the process was running.
After a few hours of debugging, watching logs and adding debug info to the app, I ended up figuring that the Vertx application was returning an 404 on the root endpoint "/". This endpoint was not a valid from my api point of view, as it has nothing to expose.
This caused HAProxy to think the server was down, making all the instances unavailable.
While this is easy to fix, it would be nice to maybe add a note on the readme file about this, or have the possibility to configure the endpoint that HAProxy uses as a health check somehow.
Thanks a lot for the cartridge :)

**Comment by cescoffier** [comment]
Hi,

Thanks for reporting the issue, it must definitely be added to the documentation.

Actually, the cartridge can define an _health_ endpoint in its metadata (not done yet, that's why "/" is used):

```
      - Frontend:      "/health"
        Backend:       ""
        Options:       { health: true }
```

This, however, cannot be overridden by applications. So, I think "/" makes more sense for most applications.

**Comment by robertoestivill** [comment]
Awesome. Good to know.
Thanks for the clarification @cescoffier
